TARGET := bootloader

OBJ_DIR := ./build/$(TARGET)
LINKER  := linkers/linker.$(TARGET).ld
OBJS    := bootloader.o bootloader_entry.o string.o uart.o printf.o sbi.o dtb.o utils.o  trap_entry.o trap.o plic.o

CFLAGS := -march=rv64gc_zbb

include ../common/common.mk
