[default_config]
assembler = "gas"
instruction_set = "riscv"

[default_config.opts]
compiler = "riscv64-unknown-elf-gcc"
compile_flags_txt = ["-march=rv64gc", "-mabi=lp64d"]
diagnostics = true
default_diagnostics = false
