TARGET  ?= kernel
OBJ_DIR ?= ./build/$(TARGET)
LINKER  ?= linkers/linker.$(TARGET).ld
OBJS    := main.o boot.o string.o uart.o printf.o sbi.o dtb.o utils.o cpio.o shell.o malloc.o trap_entry.o trap.o timer.o

CFLAGS := -march=rv64gc_zbb
CFLAGS += -DDEBUG

include ../common/common.mk
