TARGET  ?= kernel
OBJ_DIR ?= ./build/$(TARGET)
LINKER  ?= linkers/linker.$(TARGET).ld
OBJS    := main.o boot.o string.o uart.o printf.o sbi.o dtb.o utils.o cpio.o shell.o

include ../common/common.mk
